name: Deploy to Surge.sh

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          # Removido cache: 'npm' para evitar el error

      - name: Install Surge CLI
        run: npm install --global surge

      - name: Deploy to Surge
        run: surge ./ --domain ${{ github.repository_owner }}-${{ github.event.repository.name }}.surge.sh --token ${{ secrets.SURGE_TOKEN }}
        
      - name: Display deployment URL
        run: echo "✅ Deployed to https://${{ github.repository_owner }}-${{ github.event.repository.name }}.surge.sh"