name: Deploy to Surge.sh

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Install Surge CLI
        run: npm install --global surge

      - name: Deploy to Surge
        run: surge ./dist --domain mi-proyecto-genial.surge.sh --token ${{ secrets.SURGE_TOKEN }}
        # Cambia "mi-proyecto-genial" por el nombre que prefieras
        
      - name: Display deployment URL
        run: echo "Deployed to https://mi-proyecto-genial.surge.sh"