name: Deploy to Surge.sh

on:
  push:
    branches: [ "main" ]  # Se activa al hacer push a la rama main

jobs:
  deploy:
    runs-on: ubuntu-latest  # Usa un servidor Ubuntu

    steps:
      # Paso 1: Descarga el código del repositorio
      - uses: actions/checkout@v4

      # Paso 2: Instala Node.js (necesario para Surge)
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Paso 3: Instala Surge globalmente
      - run: npm install --global surge

      # Paso 4: Despliega con Surge
      - run: surge ./ --token ${{ secrets.SURGE_TOKEN }}